version: "3.8"
services:
    www:
        build: .
        container_name: api
        ports:
            - "80:80"
        working_dir: /var/www/html
        volumes:
        - ./:/var/www/html
        - ./apache.conf:/etc/apache2/sites-available/000-default.conf
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.3.0
        container_name: db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: englishdictionary
            MYSQL_USER: huy
            MYSQL_PASSWORD: huy
            MYSQL_ROOT_PASSWORD: huy
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: huy
            MYSQL_PASSWORD: huy
            MYSQL_ROOT_PASSWORD: huy